DB_ENV: development

server:
  port: 3000

# The database adaptors to use
selected_adaptors:
  persistent: couchdb 
  #cache: redis


# Individual Adaptor Settings
adaptor_settings:
  redis:
    host: 'localhost'
    port: 6379
    #password: foobar

  # really just steals options of cradle
  couchdb:
    # host information
    host: 'localhost'
    port: 5984
    #retries: 3
    #retryTimeout: 30*1000
    cache: true
    raw: false

    # Authentication Settings
    #secure: false;
    #auth:
    #  username: ''
    #  password: ''

